spring:
  application:
    name: hc-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka
feign:
  hystrix:
    enabled: true
logging:
  level:
    '[org.springframework]': INFO
    '[cn.jian]': DEBUG